# =============================
# 데이터베이스 설정 (H2 메모리 DB)
# =============================
spring:
  datasource:
    url: jdbc:h2:mem:testdb             # 메모리 DB. 애플리케이션 종료 시 데이터 사라짐
    driver-class-name: org.h2.Driver   # H2 드라이버
    username: sa                       # 기본 사용자명
    password:                          # 비밀번호 없음
# =============================
# JPA (Hibernate) 설정./gradlew bootRun
# =============================
  h2:
    console:
      enabled: true
      path: /h2-console

# =============================
# JPA (Hibernate) 설정
# =============================
  jpa:
    hibernate:
      ddl-auto: update                 # Entity 기반으로 테이블 자동 생성/수정
    show-sql: true                     # 실행되는 SQL 쿼리 콘솔 출력
    properties:
      hibernate:
        format_sql: true              # SQL 출력 포맷 정리해서 보기 좋게

# =============================
# 카카오 소셜 로그인 (OAuth2)
# =============================
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 6108d4696e9de6ee73209c208847609e       # Kakao Developers 에서 발급받은 REST API 키
            client-secret: FsfOypUc9BgWQx2zTRN6MgbU6FARptee # (보통 공란. 설정 안 하면 없어도 됨)
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"  # 로그인 완료 후 리디렉션 URL
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image  # 사용자 정보 요청 범위

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize  # 로그인 요청 URL
            token-uri: https://kauth.kakao.com/oauth/token              # 액세스 토큰 요청 URL
            user-info-uri: https://kapi.kakao.com/v2/user/me            # 사용자 정보 요청 URL
            user-name-attribute: id                                     # 사용자 고유 ID 지정